version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: db
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: mysql:8.0.21
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taxi_app
    ports:
      - "3306:3306"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge